//! A DERIVED ADMONITION TITLE ID IS STILL DERIVED WHEN THE NAMESPACE COLLIDES
//! (carve-rs#1258, sibling of markup-carve/carve-js#1336).
//!
//! `render_admonition` does not write `adm-{N}`. It writes
//! `document_ids::unique_id("adm-{N}")`, and that registry is seeded with every
//! id the document already carries - so an author who took the name the counter
//! is about to reach pushes the generated one to the next free numeric suffix.
//! The importer predicted the bare counter, looked for `adm-1` where the
//! renderer had written `adm-1-2`, and reported a drop that had not happened.
//!
//! NOTHING IS LOST IN THAT SHAPE, which is why the row is the defect. PART 9
//! §16a calls a derived drop "not a lossy decision" and requires it to be
//! silent: the next render regenerates the id. A report that OVERSTATES is the
//! mirror of markup-carve/carve-php#1579, which was accepted for removing three
//! rows describing drops that never happened, and both directions make the
//! report less usable.
//!
//! THE FIX IS IN THE PREDICATE, NOT THE RENDERER. The renderer is right to
//! dedup - two elements sharing a DOM id is invalid HTML - so what the importer
//! has to model is the ALLOCATION rather than the counter. The match therefore
//! stays an equality match on the value the renderer would actually write;
//! matching the shape `adm-N` is the guess the rule does not make, and
//! `a_derived_accessible_name_does_not_come_back.rs` pins that separately.

use carve::{html_to_carve, HtmlImportOptions};

fn import(html: &str) -> String {
    html_to_carve(html, &HtmlImportOptions::default())
        .expect("import")
        .value
}

fn diagnostics(html: &str) -> Vec<String> {
    html_to_carve(html, &HtmlImportOptions::default())
        .expect("import")
        .report
        .diagnostics
        .into_iter()
        .map(|d| format!("{} | {}", d.code.as_str(), d.message))
        .collect()
}

/// The engine's own output for the colliding source, so the test cannot drift
/// from what the renderer writes.
const SOURCE: &str = "{#adm-1}\nx\n\n::: note \"A\"\nb\n:::\n";

#[test]
fn the_renderer_suffixes_the_derived_id_when_the_author_took_the_name() {
    let out = carve::to_html(SOURCE);
    assert!(out.contains("id=\"adm-1\""), "{out}");
    assert!(
        out.contains("<p class=\"admonition-title\" id=\"adm-1-2\">A</p>"),
        "{out}"
    );
    assert!(out.contains("aria-labelledby=\"adm-1-2\""), "{out}");
}

/// The row that should not be there. Before the fix the report carried
/// `Dropped id="adm-1-2" on <p>: an admonition title has no attribute slot`,
/// which describes a loss that does not happen: the id is regenerated by the
/// next render, which is what makes it derived.
#[test]
fn a_suffixed_derived_title_id_is_dropped_in_silence() {
    let html = carve::to_html(SOURCE);
    assert_eq!(diagnostics(&html), Vec::<String>::new());
}

/// And the document still round-trips to its own source, so the id really was
/// regenerated rather than baked in.
#[test]
fn a_suffixed_derived_title_id_round_trips_to_the_source_that_produced_it() {
    let html = carve::to_html(SOURCE);
    let source = import(&html);
    assert_eq!(source, SOURCE);
    assert!(!source.contains("adm-1-2"), "{source}");
}

/// SEVERAL TITLES, so the allocation is exercised as a sequence rather than as
/// one lookup: the second title's base is `adm-2`, which is free, and the first
/// one's suffix must not have consumed it.
#[test]
fn a_collision_on_one_title_does_not_move_the_next_one() {
    let source = "{#adm-1}\nx\n\n::: note \"A\"\nb\n:::\n\n::: tip \"B\"\nc\n:::\n";
    let html = carve::to_html(source);
    assert!(
        html.contains("<p class=\"admonition-title\" id=\"adm-1-2\">A</p>"),
        "{html}"
    );
    assert!(
        html.contains("<p class=\"admonition-title\" id=\"adm-2\">B</p>"),
        "{html}"
    );
    assert_eq!(diagnostics(&html), Vec::<String>::new());
    assert_eq!(import(&html), source);
}

/// THE AUTHOR TAKES THE SUFFIX TOO. `adm-1` and `adm-1-2` both spoken for
/// leaves `adm-1-3`, because the registry skips candidates already reserved -
/// a prediction that stopped at the first suffix would miss this one exactly
/// the way the bare counter missed the last.
#[test]
fn a_derived_title_id_skips_every_name_the_author_already_took() {
    let source = "{#adm-1}\nx\n\n{#adm-1-2}\ny\n\n::: note \"A\"\nb\n:::\n";
    let html = carve::to_html(source);
    assert!(
        html.contains("<p class=\"admonition-title\" id=\"adm-1-3\">A</p>"),
        "{html}"
    );
    assert_eq!(diagnostics(&html), Vec::<String>::new());
    assert_eq!(import(&html), source);
}

/// The uncollided case is unchanged - the whole point is that this reports
/// nothing where nothing was lost, and it did already when no name collided.
#[test]
fn an_uncollided_derived_title_id_is_still_dropped_in_silence() {
    let source = "::: note \"A\"\nx\n:::\n";
    let html = carve::to_html(source);
    assert!(
        html.contains("<p class=\"admonition-title\" id=\"adm-1\">A</p>"),
        "{html}"
    );
    assert_eq!(diagnostics(&html), Vec::<String>::new());
    assert_eq!(import(&html), source);
}

/// AN ID NO ALLOCATION REACHES IS STILL REPORTED. Modelling the namespace must
/// not turn the rule into "any counter-shaped id on a counted title": a title
/// whose id is neither the counter's value nor any suffix of it was authored,
/// has nowhere to go, and is a real loss.
#[test]
fn a_title_id_the_allocation_does_not_reach_is_still_reported() {
    let html = "<aside class=\"admonition note\" aria-labelledby=\"adm-7\">\
                <p class=\"admonition-title\" id=\"adm-7\">A</p><p>x</p></aside>";
    assert_eq!(import(html), "::: note \"A\"\nx\n:::\n");
    assert_eq!(
        diagnostics(html),
        vec![
            "attribute-dropped | Dropped id on <p>: an admonition title has no attribute slot"
                .to_owned()
        ],
    );
}

/// A SUFFIX WITH NO COLLISION BEHIND IT is authored too. `adm-1-2` on the first
/// title of a document that contains no `adm-1` is a value the renderer would
/// never have produced there, so it stays a reported drop - the equality match
/// is on what the allocation WOULD write, not on what a suffix looks like.
#[test]
fn a_suffix_shaped_id_with_nothing_to_collide_with_is_still_reported() {
    let html = "<aside class=\"admonition note\" aria-labelledby=\"adm-1-2\">\
                <p class=\"admonition-title\" id=\"adm-1-2\">A</p><p>x</p></aside>";
    assert_eq!(
        diagnostics(html),
        vec![
            "attribute-dropped | Dropped id on <p>: an admonition title has no attribute slot"
                .to_owned()
        ],
    );
}
