#!/usr/bin/env python3
"""Generate src/wire_fields.rs from the pinned tests/spec/resources/ast-schema.json.

PART 12 section 11 makes an ingest refuse a property the schema does not name,
which needs the named set AT RUNTIME - and the schema lives in the spec
submodule, which the published crate does not ship. So the map is generated and
committed, with a test that regenerates it and compares: one source of truth
(the schema), one artifact, and a diff the moment the two drift.

Writing the list by hand would be the schema expressed a second time in code,
and the failure mode of a stale copy is REFUSING VALID INPUT - which is why this
is a script rather than a table someone maintains.

    python3 tools/generate-wire-fields.py [--check]

Exit codes: 0 when the committed file matches, 1 when it does not (--check), 2
on a usage/setup error.
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "tests/spec/resources/ast-schema.json"
TARGET = ROOT / "src/wire_fields.rs"

HELPERS = ("attrs", "pos")


def render(schema: dict) -> str:
    defs = schema.get("$defs", {})
    by_type: dict[str, list[str]] = {}
    for definition in defs.values():
        properties = definition.get("properties")
        if not properties:
            continue
        type_const = properties.get("type", {}).get("const")
        if not isinstance(type_const, str):
            continue
        if definition.get("additionalProperties") is not False:
            raise SystemExit(f"{type_const} is not closed in the schema; section 11 has nothing to check against")
        by_type[type_const] = sorted(properties)

    helpers: dict[str, list[str]] = {}
    for name in HELPERS:
        definition = defs.get(name, {})
        if definition.get("additionalProperties") is not False:
            raise SystemExit(f"{name} is not closed in the schema; section 11 has nothing to check against")
        helpers[name] = sorted(definition["properties"])

    def table(entries: dict[str, list[str]], name: str, doc: str) -> str:
        rows = "".join(
            '    ("%s", &[%s]),\n' % (key, ", ".join('"%s"' % f for f in fields))
            for key, fields in sorted(entries.items())
        )
        # `rustfmt::skip` because the generator, not rustfmt, owns this
        # layout: without it the two disagree and the drift check fails on a
        # file nobody edited.
        return (
            "/// %s\n"
            "#[rustfmt::skip]\n"
            "pub(crate) const %s: &[(&str, &[&str])] = &[\n%s];\n" % (doc, name, rows)
        )

    return (
        "// GENERATED by tools/generate-wire-fields.py from the pinned\n"
        "// tests/spec/resources/ast-schema.json. Do not edit: run the tool.\n"
        "//\n"
        "// PART 12 section 11 - a property the schema does not name is refused on\n"
        "// ingest - needs the named set at runtime, and the schema is not shipped\n"
        "// with the crate.\n"
        "\n"
        + table(by_type, "WIRE_FIELDS", "Properties the schema names for each node type.")
        + "\n"
        + table(
            helpers,
            "WIRE_HELPER_FIELDS",
            "Properties the schema names for the objects that hang off a node.",
        )
    )


def main() -> int:
    if not SCHEMA.exists():
        print(f"{SCHEMA} is missing; run `git submodule update --init`", file=sys.stderr)
        return 2
    generated = render(json.loads(SCHEMA.read_text()))
    if "--check" in sys.argv[1:]:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current == generated:
            return 0
        print(f"{TARGET} is stale; run `python3 tools/generate-wire-fields.py`", file=sys.stderr)
        return 1
    TARGET.write_text(generated)
    print(f"{TARGET} written from {SCHEMA}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
