// GENERATED by tools/generate-wire-fields.py from the pinned
// tests/spec/resources/ast-schema.json. Do not edit: run the tool.
//
// PART 12 section 11 - a property the schema does not name is refused on
// ingest - needs the named set at runtime, and the schema is not shipped
// with the crate.

/// Properties the schema names for each node type.
#[rustfmt::skip]
pub(crate) const WIRE_FIELDS: &[(&str, &[&str])] = &[
    ("abbreviation", &["abbr", "attrs", "expansion", "pos", "type"]),
    ("abbreviation_def", &["abbr", "attrs", "expansion", "pos", "type"]),
    ("admonition", &["attrs", "children", "kind", "label", "pos", "title", "type"]),
    ("autolink", &["attrs", "href", "pos", "text", "type"]),
    ("block_quote", &["attrs", "children", "pos", "type"]),
    ("caption_number", &["attrs", "n", "pos", "type"]),
    ("citation_group", &["attrs", "items", "mode", "pos", "raw", "type"]),
    ("code", &["attrs", "pos", "type", "value"]),
    ("code_block", &["attrs", "content", "header", "label", "lang", "pos", "type"]),
    ("comment", &["attrs", "block", "content", "pos", "type"]),
    ("critic_comment", &["attrs", "pos", "text", "type"]),
    ("definition_description", &["attrs", "children", "pos", "type"]),
    ("definition_list", &["attrs", "items", "pos", "type"]),
    ("definition_term", &["attrs", "children", "pos", "type"]),
    ("delete", &["attrs", "children", "pos", "type"]),
    ("div", &["attrs", "children", "label", "pos", "type"]),
    ("document", &["children", "srcByteLength", "type"]),
    ("emphasis", &["attrs", "children", "pos", "type"]),
    ("escaped_text", &["attrs", "pos", "type", "value"]),
    ("figure", &["attrs", "caption", "pos", "shortCaption", "target", "type"]),
    ("figure_group", &["attrs", "caption", "children", "pos", "type"]),
    ("footnote", &["attrs", "children", "label", "pos", "type"]),
    ("footnote_ref", &["attrs", "id", "number", "pos", "type"]),
    ("frontmatter", &["content", "format", "pos", "type"]),
    ("hard_break", &["attrs", "pos", "type"]),
    ("heading", &["attrs", "children", "level", "pos", "type"]),
    ("heading_ref", &["attrs", "href", "pos", "target", "type"]),
    ("highlight", &["attrs", "children", "pos", "type"]),
    ("image", &["alt", "attrs", "pos", "rawRef", "ref", "src", "title", "type"]),
    ("inline_extension", &["attrs", "content", "name", "pos", "type"]),
    ("inline_footnote", &["attrs", "inline", "number", "pos", "type"]),
    ("insert", &["attrs", "children", "pos", "type"]),
    ("line_block", &["attrs", "children", "pos", "type"]),
    ("link", &["attrs", "children", "href", "pos", "rawRef", "ref", "title", "type"]),
    ("link_reference_definition", &["attrs", "href", "label", "pos", "title", "type"]),
    ("list", &["attrs", "bareMarker", "bulletChar", "delim", "items", "olType", "ordered", "pos", "start", "tight", "type"]),
    ("list_item", &["attrs", "checked", "children", "pos", "type"]),
    ("literal_inline", &["attrs", "content", "pos", "type"]),
    ("math", &["attrs", "content", "display", "pos", "type"]),
    ("mention", &["attrs", "pos", "type", "user"]),
    ("paragraph", &["attrs", "children", "pos", "type"]),
    ("raw_block", &["attrs", "content", "format", "pos", "type"]),
    ("raw_inline", &["attrs", "content", "format", "pos", "type"]),
    ("smart_punctuation", &["attrs", "glyph", "kind", "pos", "type", "value"]),
    ("soft_break", &["attrs", "pos", "type"]),
    ("span", &["attrs", "children", "pos", "type"]),
    ("strike", &["attrs", "children", "pos", "type"]),
    ("strong", &["attrs", "boldItalic", "children", "pos", "type"]),
    ("subscript", &["attrs", "children", "pos", "type"]),
    ("substitution", &["attrs", "newText", "oldText", "pos", "type"]),
    ("superscript", &["attrs", "children", "pos", "type"]),
    ("symbol", &["attrs", "name", "pos", "type"]),
    ("table", &["attrs", "caption", "pos", "rowGroups", "rows", "shortCaption", "type"]),
    ("table_cell", &["align", "attrs", "children", "header", "pos", "span", "type"]),
    ("table_row", &["attrs", "cells", "pos", "type"]),
    ("tag", &["attrs", "name", "pos", "type"]),
    ("text", &["attrs", "pos", "type", "value"]),
    ("thematic_break", &["attrs", "marker", "pos", "type"]),
    ("underline", &["attrs", "children", "pos", "type"]),
];

/// Properties the schema names for the objects that hang off a node.
#[rustfmt::skip]
pub(crate) const WIRE_HELPER_FIELDS: &[(&str, &[&str])] = &[
    ("attrs", &["classes", "id", "keyValues", "order"]),
    ("pos", &["endColumn", "endLine", "endOffset", "startColumn", "startLine", "startOffset"]),
    ("rowGroups", &["bodies", "footRows", "headRows"]),
];

/// Properties the schema names for an untyped record in an array,
/// keyed by the `type.property` that holds it.
#[rustfmt::skip]
pub(crate) const WIRE_UNTYPED_ARRAY_FIELDS: &[(&str, &[&str])] = &[
    ("citation_group.items", &["key", "locator", "locatorLabel", "locatorValue", "number", "prefix", "suffix", "suppressAuthor", "useIndex"]),
    ("table.rowGroups.bodies", &["attrs", "bodyRows", "headRows", "rowHeadColumns"]),
];
